version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn app:app --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on: 
      - db

  frontend:
    build: 
      context: ./frontend
    depends_on: 
      - backend

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: 
      - ./backend/.env

  proxy:
    build: ./nginx
    ports: 
      - 80:80
    depends_on:
      - backend
    restart: "on-failure"

volumes:
  postgres_data:
  